# Generated by Django 5.1.3 on 2024-11-10 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
